apiVersion: v1
kind: Service
metadata:
  name: solar-simulator
  namespace: default
  labels:
    app: solar-simulator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: solar-simulator
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
