apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-simulator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/UltraDard/solar-monitoring-gitops.git
    targetRevision: HEAD
    path: apps/solar-simulator
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/UltraDard/solar-monitoring-gitops.git
    targetRevision: HEAD
    path: monitoring
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
